duandautienx/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace duandautienx.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

duandautienx/Pages/Formbinding.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace duandautienx.Pages
{
    public class FormbindingModel : PageModel
    {
        public string Message { get; private set; }
        public void OnPost(String fullname, string email, int age) => Message = age < 10 ?
            $"Sorry, {fullname} . You cannot" :
            $"Hello, {fullname} . Thank you ";
        public void OnGet()
        {
        }
    }
}

duandautienx/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace duandautienx.Pages
{
    public class IndexModel : PageModel
    {
        public string Message { get; set; }
        public void OnGet()
        {
            Message = "this is a Get request";
        }
        public void OnPost()
        {
            Message = "this is a Post request";
        }
    }
}

duandautienx/Pages/Multication.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace duandautienx.Pages
{
    public class MulticationModel : PageModel
    {
        public string Message { get; set; } = "Default Get method";
        public void OnPostRegister () => Message = "Post register fired!";
        public void OnPostRegisterInfo() => Message = "Post Register Info fired";
        public void OnGetClear() => Message = "Get Clear fired";
        public void OnGetReset() => Message = "Get Reset fired";
    }
}

duandautienx/Pages/Multiform.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace duandautienx.Pages
{
    public class MultiformModel : PageModel
    {
        public string Message { get; set; } = "Initial Request";
        public void OnGet()
        {
        }
        public void OnPost()
        {
            Message = "Form Post";
        }
        public void OnPostDelete()
        {
            Message = "Delete Handler fired";
        }
        public void OnPostEdit(int id)
        {
            Message = "Edit Handler fired";
        }
        public void OnPostView(int id)
        {
            Message = $"View Handler fired {id}";
        }

    }
}

duandautienx/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace duandautienx.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

duandautienx/Pages/UrlBingDing.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace duandautienx.Pages
{
    public class UrlBingDingModel : PageModel
    {
/*        [BindProperty (SupportsGet = true)]
        public int age { get; set; }*/
        public string Message { get; set; }
        public void OnGet(string fullname, string email, int age) => Message = age < 18 ?
            $"Sorry" :
            $"Hello";
    }
}

duandautienx/Pages/text.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace duandautienx.Pages
{
    public class textModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

duandautienx/Pages/Formbinding.cshtml
@page
@model duandautienx.Pages.FormbindingModel
@{
    ViewData["Title"] = "FromBinDing";
    var method = Request.Method.ToUpper();
}

@if (method == "GET"){ 
    <form class="center border border-light p-3 w-50" method="post">
        <div class="text-center">
            <p class="h4 mb-4">Subsribe</p>
            <p>...</p>
        </div>
        <input name="fullname" type="text" placeholder="name" class="form-control mb-2" />
        <input name="email" type="email" placeholder="email" class="form-control mb-2" />
        <input name="age" type="number" placeholder="age" class="form-control mb-2" />
        <button type="submit" class="btn btn-info btn-block">Register</button>
    </form> 
}
            else if (method == "POST"){ 
    <div class="center text-center border border-success">
        <p class="h5">@Model.Message</p>
    </div>
}

duandautienx/Pages/Index.cshtml
@page
@model duandautienx.Pages.IndexModel;
@{
    ViewData["Title"] = "Home page";
}

<h3>@Model.Message</h3>
<form method="post">
    <p><button class="btn btn-primary" type="submit">Send Post Request</button></p>
</form>
<p><a href="/" class="btn btn-primary">Send Get Request</a></p>

duandautienx/Pages/Multication.cshtml
@page
@model duandautienx.Pages.MulticationModel
@{
}

<form method="post">
    <button asp-page-handler="register">Register</button>
    <button asp-page-handler="registerinfor">Register Info</button>
</form>
<a class="btn btn-danger" asp-page-handler="clear">Clear All</a>
<a class="btn btn-info" asp-page-handler="reset">Reset All</a>

<h3>@Model.Message</h3>

duandautienx/Pages/Multiform.cshtml
@page   
    @*"{handler}/{id}" delete/10 *@
@model duandautienx.Pages.MultiformModel
@{
    ViewData["Title"] = "Multiform";
}

<div class="row">
    <div class="col-sm">
        <form asp-page-handler="edit" method="post">
            <button class="btn btn-outline-danger">Edit</button>
        </form>
    </div>
    <div class="col-sm">
        @*        <form asp-page-handler="delete" method="post">
            <button class="btn btn-outline-primary">Delete</button>
        </form>*@
        <form asp-page-handler="delete" asp-route-id="10" method="post">@*delete?id=10*@
            <button class="btn btn-default">Delete</button>
        </form>
    </div>
    <div class="col-sm">
        <form asp-page-handler="view" method="post">
            <button class="btn btn-outline-secondary">View</button>
            <input type="hidden" name="id" value="3" />
        </form>
    </div>
</div>

<h3>@Model.Message</h3>

duandautienx/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - duandautienx</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3" style="background-color:forestgreen">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">duandautienx</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Multiform">Multiform</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Multication">Multication</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Formbinding">Formbinding</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/UrlBingDing">UrlBingDing</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Text">Time Now</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - duandautienx - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

duandautienx/Pages/UrlBingDing.cshtml
@page
@model duandautienx.Pages.UrlBingDingModel
@{
    ViewData["Title"] = "UrlBinDing";
}

<strong>@Model.Message</strong>

duandautienx/Pages/text.cshtml
@page
@model duandautienx.Pages.textModel
@{
}

<h1 style="color:aquamarine">Time</h1>
<p>Bây giờ là @DateTime.Now</p>
<p>Giờ này tuần trước là: @(DateTime.Now - TimeSpan.FromDays(7))</p>
<p>@TimeSpan.FromDays(1)</p>
<p>@TimeSpan.FromDays(2)</p>
<p>@TimeSpan.FromDays(3)</p>
<p>Bây giờ là @DateTime.Now</p>
<p>1 + 1 = @(1+1)</p>
<p>Pi = @Math.PI</p>
<p>E = @Math.E</p>
<p>Cos = @Math.Cos(10)</p>
<p>... = @Math.Abs(2)</p>